services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: always
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
