services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./storage:/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`swaye.dev`)"
    networks:
      - default
networks:
  default:
    external: true
    name: proxy_default
