name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
        PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
        PROJECT_PATH: /apps/portfolio
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        ssh -o StrictHostKeyChecking=no $PRODUCTION_USER@$PRODUCTION_HOST << EOF
          cd /apps
          if [ ! -d "$PROJECT_PATH" ]; then
            git clone https://github.com/swayechateau/portfolio.git $PROJECT_PATH
          else
            cd $PROJECT_PATH
            git pull
          fi
          cd $PROJECT_PATH
          docker-compose up -d --build
        EOF
